# Project information
site_name: YSH NOTE
site_url: https://ysheee.github.io/

# Repository
#repo_name: YSHeee/YSHeee.github.io
#repo_url: https://github.com/YSHeee/YSHeee.github.io


## Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  logo: assets/images/tree.png
  favicon: assets/images/clover.png
  font:
    text: Gowun Dodum
    code: Roboto mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    # - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    #- toc.integrate
    # - header.autohide
    - content.code.annotate
    - content.code.copy
    - content.tabs.link


## Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YSHeee
      name: Github
  analytics:
    provider: google
    property: G-K6PD1RZ6VF
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
  - stylesheets/extra.css
plugins:
  - search




## Extension
markdown_extensions:
  - attr_list
  - def_list
  - tables
  - meta
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true



## Page tree
nav:
  - Home: index.md
  - Web:
    - HTTP Status Code: web/status-code.md 
  - Linux: 
    - Directory Structure: linux/directory-structure.md
    - Command: linux/command.md
    - SSH: linux/ssh.md
    - Note:
      - vim: linux/note/vim.md
      - Nvidia-command: linux/note/nvidia.md
      - tmux: linux/note/tmux.md
  - Docker:
    - Basic: docker/basic.md
    - Command:
      - Base Command: docker/command/command.md
      - Compose Command: docker/command/compose.md
      - Dockerfile: docker/command/dfile.md
      - Compose-yml: docker/command/docker-compose-yml.md
      - Buildx: docker/command/buildx.md
    - Note:
      - Install: docker/note/installation.md
      - Registry: docker/note/registry.md
      - Portainer: docker/note/portainer.md
      - Multi-stage:
        - Multi Stage Builds: docker/note/multiS.md
        - Practice: docker/note/multiS2.md
      - Multi-architecture: docker/note/multiA.md
      - Buildkit: docker/note/buildkit.md
      - BuildX: docker/note/buildx.md
      - Best-practice: docker/note/best-practice.md
    - System Run:
      - Monitoring: docker/running/monitoring.md
      - ELK: docker/running/elk.md
      - Others:
        - docker/running/sorry.md
        - wordpress-maria-admin: docker/running/wmp.md
        - django-postgre-admin: docker/running/dpp.md
        - nginx-flask-mysql-admin: docker/running/nfmp.md
        - react-express-mongo-me: docker/running/remm.md
        - etc: docker/running/etc.md
  - FastAPI:
    - Best-Practice: fastapi/best-practice.md
    - RestAPI:
      - fastapi/design.md
  - Language:
    - Python:
      - Python : language/python/python.md
      - Style Guide: language/python/style-guide.md
      - Basic:
        - Variable: language/python/basic/variable.md
        - Operator: language/python/basic/operator.md
        - String: language/python/basic/string.md
        - List: language/python/basic/list.md
        - Dictionary: language/python/basic/dictionary.md
        - Set: language/python/basic/set.md
        - Tuple : language/python/basic/tuple.md
        - Exception : language/python/basic/exception.md
        - Function : language/python/basic/function.md
        - File : language/python/basic/file.md
      - Advanced:
        - Class : language/python/advanced/class.md
        - Closure : language/python/advanced/closure.md
        - Coroutine : language/python/advanced/coroutine.md
        - Modules : language/python/advanced/modules.md
        - Package : language/python/advanced/package.md
        - rator*3 : language/python/advanced/rator.md
        - Regular Expressions : language/python/advanced/re.md
        - Type Hints : language/python/advanced/type-hints.md
        - Concurrency: language/python/advanced/concurrency.md
      - Note : 
        - 1 : language/python/note/1.md
    - Java:
      - Java : language/java/java.md
      - Basic :
        - JVM : language/java/basic/jvm.md
        - Syntax : language/java/basic/syntax.md
        - Variable : language/java/basic/variable.md
        - Data Types : language/java/basic/data-types.md
        - Operator : language/java/basic/operator.md
        - Conditionals : language/java/basic/conditionals.md
        - Loop : language/java/basic/loop.md
        - Array : language/java/basic/array.md
        - Method : language/java/basic/method.md
        - Modifier : language/java/basic/modifier.md
        - Class : language/java/basic/class.md
        - Inheritance : language/java/basic/inheritance.md
        - Polymorphism : language/java/basic/polymorphism.md
        - Exception : language/java/basic/exception.md
        - JAVA API : language/java/basic/java-api.md
      - Advanced:
        - Generic : language/java/advanced/generic.md
        - Collection : language/java/advanced/collection.md
        - IO : language/java/advanced/io.md
        - Thread : language/java/advanced/thread.md
        - Lambda : language/java/advanced/lambda.md
        - Stream : language/java/advanced/stream.md
      - Style-Guide : language/java/style-guide.md
      - Note : 
        - 1 : language/java/note/1.md
  - DB: 
    - Basic: db/basic.md
    - Mysql: 
      - Syntax: db/mysql/syntax.md
      - DML: db/mysql/dml.md 
      - Cheat Sheet: db/mysql/cheat-sheet.md
  - Git:
    - Git : git/git.md
    - Git Flow : git/git-flow.md
    - Commit Convention : git/commit-convention.md
  - Note:
    - Bookmark: note/bookmark.md
    - Setting: note/setting.md
    - MKdocs: note/mkdocs/mkdocs.md
    - VMware: note/vmware/VMware.md
    - PM2: note/pm2.md
  - Programmers: 
    - Python:
      - Level 0: programmers/python/level0.md
    - Java:
      - Level 0: programmers/java/java_example.md
    - Mysql:
      - Level 1: programmers/mysql/level1.md
    - MSA Group:
      - 9월 : programmers/group/september.md
  - Interview:
    - Link: interview/link.md
    - SelfPR: interview/pr.md
    - Tech: 
      - Experience: interview/tech-experience.md
      - CS: interview/tech-cs.md
      - Python: interview/tech-python.md
      - Deploy : interview/tech-deploy.md
  - Nice to meet you : visitor.md
