# Project information
site_name: YSH NOTE
site_url: "https://ysheee.github.io/"

# Repository
repo_name: YSHeee/YSHeee.github.io
repo_url: https://github.com/YSHeee/YSHeee.github.io

# Configuration
theme:
  name: material
  palette:
    primary: cyan
