# Project information
site_name: YSH NOTE
site_url: "https://ysheee.github.io/"

# Repository
#repo_name: YSHeee/YSHeee.github.io
#repo_url: https://github.com/YSHeee/YSHeee.github.io


## Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  logo: assets/images/tree.png
  favicon: assets/images/clover.png
  font:
    text: Gowun Dodum
    code: Roboto mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    # - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    #- toc.integrate
    # - header.autohide
    - content.code.annotate
    - content.code.copy
    - content.tabs.link


## Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YSHeee
      name: Github
  comments:
    enabled: true
    # defaults to utterances unless replaced with mode: giscus
    mode: utterances
    type: issues
extra_css:
  - stylesheets/extra.css
plugins:
  - search


## Extension
markdown_extensions:
  - attr_list
  - def_list
  - tables
  - meta
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true



## Page tree
nav:
  - Home: index.md
  - Web:
    - HTTP Status Code: web/status-code.md 
  - Linux: 
    - Directory Structure: linux/directory-structure.md
  - Docker:
    - Basic: docker/basic.md
    - Command:
      - Base Command: docker/command/command.md
      - Compose Command: docker/command/compose.md
      - Dockerfile: docker/command/dfile.md
      - Compose-yml: docker/command/docker-compose-yml.md
      - Buildx: docker/command/buildx.md
    - Note:
      - Install: docker/note/installation.md
      - Registry: docker/note/registry.md
      - Portainer: docker/note/portainer.md
      - Multi-stage:
        - Multi Stage Builds: docker/note/multiS.md
        - Practice: docker/note/multiS2.md
      - Multi-architecture: docker/note/multiA.md
      - Temp:
        - Buildkit: docker/note/buildkit.md
        - BuildX: docker/note/buildx.md
        - Best-practice: docker/note/best-practice.md
    - System Run:
      - Monitoring: docker/running/monitoring.md
      - ELK: docker/running/elk.md
      - Others:
        - docker/running/sorry.md
        - wordpress-maria-admin: docker/running/wmp.md
        - django-postgre-admin: docker/running/dpp.md
        - nginx-flask-mysql-admin: docker/running/nfmp.md
        - react-express-mongo-me: docker/running/remm.md
        - etc: docker/running/etc.md
  - FastAPI:
    - Best-Practice: fastapi/best-practice.md
    - RestAPI:
      - fastapi/design.md
  - Language:
    - Python:
      - Python : python/python.md
      - Style Guide: python/style-guide.md
      - Basic:
        - Variable: python/basic/variable.md
        - String: python/basic/string.md
        - List: python/basic/list.md
        - Dictionary: python/basic/dictionary.md
        - Set: python/basic/set.md
        - Tuple : python/basic/tuple.md
        - Exception : python/basic/exception.md
        - Function : python/basic/function.md
        - File : python/basic/file.md
      - Advanced:
        - Class : python/advanced/class.md
        - Closure : python/advanced/closure.md
        - Coroutine : python/advanced/coroutine.md
        - Modules : python/advanced/modules.md
        - Package : python/advanced/package.md
        - rator*3 : python/advanced/rator.md
        - Regular Expressions : python/advanced/re.md
        - Type Hints : python/advanced/type-hints.md
        - Concurrency: python/advanced/concurrency.md
    - Java:
      - java: java/java.md
      - Style-Guide : java/style-guide.md
  - Git:
    - Git : git/git.md
    - Git Flow : git/git-flow.md
    - Commit Convention : git/commit-convention.md
  - Temp:
    - MKdocs: temp/mkdocs/mkdocs.md
    - VMware: temp/vmware/VMware.md
    - PM2: temp/pm2.md
    - Setting: temp/setting.md
  - TIL:
    - Setting: til/set.md
    - Day1: til/day1.md
  - Programmers: 
    - Python:
      - Level 0: 
        - 1 : programmers/python/level0.md
    - Java:
      - Level 0: 
        - 1 : programmers/python/level0.md
    - Mysql:
      - Level 0: 
        - 1 : programmers/python/level0.md
  - Interview:
    - Link: interview/link.md
    - SelfPR: interview/pr.md
    - Tech: 
      - Experience: interview/tech-experience.md
      - CS: interview/tech-cs.md
      - Python: interview/tech-python.md
      - Deploy : interview/tech-deploy.md
  - Bookmark: bookmark.md
