# Project information
site_name: YSH NOTE
site_url: "https://ysheee.github.io/"

# Repository
#repo_name: YSHeee/YSHeee.github.io
#repo_url: https://github.com/YSHeee/YSHeee.github.io


## Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light mode 
  logo: assets/images/tree.png
  favicon: assets/images/clover.png
  font:
    text: Roboto
    code: Roboto mono
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.integrate
    - header.autohide
    - content.code.annotate
    - content.code.copy


## Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YSHeee
      name: Github
extra_css:
  - stylesheets/extra.css
plugins:
  - search


## Extension
markdown_extensions:
  - attr_list
  - def_list
  - tables
  - meta
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc: 
      permalink: true


## Page tree
nav:
  - Home: index.md
  - Linux: linux/example.md
  - Docker:
    - Basic: docker/basic.md
    - Install: docker/installation.md
    - Command: 
      - Base Command: docker/command.md
      - Compose Command: docker/compose.md
      - Dockerfile: docker/dfile.md
  - Temp:
    - Shortcut: temp/shortcut.md
    - MKdocs: temp/mkdocs/mkdocs.md
    - VMware: temp/vmware/VMware.md
    